services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/ubuntu/appdata/mongodb:/data/db
  server:
    build: .
    ports:
      - 12311:3000
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - APP_DATA=${APP_DATA}
    volumes:
      - ${APP_DATA}:/app/src/public/uploads
