services:
  db:
    image: mongo
    ports: 
      - 27017:27017
  server:
    build:
      context: .
      args:
        MONGO_URL: "mongodb://db"
        NEXTAUTH_SECRET: A_CHANGE
        AUTH_URL: CHANGE_ME
    ports: 
      - 12311:3000
    depends_on:
      - db